language: node_js

node_js:
- "4"

branches:
  only:
  - master

install:
- npm install

notifications:
  email:
    recipients:
    - liuderchi@gmail.com
    on_success: never
    on_failure: change

script: npm test
